version: '3'
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "5000:5000"
    environment:
      - NODE_NAME=A
      - NODE_PORT=5000

  node2:
    build: .
    container_name: node2
    ports:
      - "5001:5001"
    environment:
      - NODE_NAME=B
      - NODE_PORT=5001

  node3:
    build: .
    container_name: node3
    ports:
      - "5002:5002"
    environment:
      - NODE_NAME=C
      - NODE_PORT=5002
